server:
  port: 9080

spring:
  application:
    name: mcp-gateway-management

  datasource:
    url: jdbc:mysql://localhost:3306/mcp_gateway?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  # WebFlux 配置
  webflux:
    base-path: /

# MyBatis配置
mybatis:
  type-aliases-package: org.jdt.mcp.gateway.core.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    org.jdt.mcp.gateway: DEBUG
    org.apache.ibatis: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.web.reactive: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/management.log

# 管理配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Reactor调度器配置
reactor:
  netty:
    # 配置IO线程数
    ioWorkerCount: 4
  schedulers:
    # 配置弹性调度器线程数
    bounded-elastic-size: 20